name: goffix
description: GOFFIX Was Created By Engineers. We Are Entrepreneurs, All Passionate About Growing Our Exclusive Network Of The Top Freelance Service Of Doctors, Plumbers Engineers ,Software Developers, Designers, Finance Experts, And Project Managers Etc., In India. As A Leader In Creative, Digital, Marketing, And Technical Solutions, We Pick The Right Talent For You Anywhere In The World.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.2.1+18

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_local_notifications: ^5.0.0+4

  # http: ^0.12.2
  http: ^0.13.0
  easy_container: ^1.0.4
  intl_phone_field: ^3.1.0
  firebase_phone_auth_handler: ^1.0.6
  shared_preferences: any
  #
  # intl: ^0.17.0
  # firebase_core: ^0.4.4+3
  # firebase_auth: ^0.18.4+1
  percent_indicator: ^4.2.3
  curved_navigation_bar: ^1.0.3
  flutter_speed_dial: ^7.0.0
  rflutter_alert: ^2.0.7
#  firebase_core: ^1.19.1
  toast: ^0.3.0
  # intl: ^0.16.0
  intl: ^0.18.0
  horizontal_calendar: ^1.0.2
  vin_decoder: ^0.2.1-nullsafety
  flutter_layout_grid: ^2.0.6
  # vin_decoder: ^0.1.3
#  carousel_pro: ^1.0.0
  sqflite: ^2.3.3
  path_provider:
  popup_menu: ^2.0.0
  date_picker_timeline: ^1.2.5
#  share: ^0.6.5+4
  # jiffy: ^3.0.1
#  jiffy: ^6.3.0
  liquid_pull_to_refresh: ^3.0.1
  popover: ^0.3.0
  url_launcher: ^6.0.1
  connectivity: ^3.0.6
  provider: ^6.0.3
  # connectivity_widget: ^0.1.8
  # slider_button: ^1.0.0
  slider_button: ^2.0.0
  # fluttertoast: ^8.0.8
  # image_picker_platform_interface: ^2.0.0
  # flutter_form_builder: ^4.2.0
  # flutter_form_builder: ^4.2.0
  # flutter_form_builder: ^5.0.0-alpha.1
  # flutter_form_builder: ^5.0.0
  # flutter_typeahead: ^3.1.1
  # validators: ^2.0.1
  # flutter_form_builder: ^7.0.0
  # flutter_form_bloc: ^0.20.6
  # flutter_form_builder: ^7.0.0
  # flutter_form_builder:
  #   # git: https://github.com/Sportner/flutter_form_builder.git
  #   git: https://github.com/Sportner/flutter_form_builder.git
  flutter_form_builder: ^9.2.1
#  form_builder_validators: ^8.9.0
  flutter_typeahead: ^3.1.1
  pinput: ^2.2.11
  shimmer: ^2.0.0
#  smooth_star_rating: ^1.1.1
  auto_size_text: ^3.0.0

#  otp_screen: ^0.0.3
  super_tooltip: ^2.0.7
  carousel_slider: ^4.2.1
  # flutter_datetime_picker: ^1.5.1
  # image_picker: ^0.7.3
  image_picker: ^0.7.4
  introduction_screen: ^3.0.2
  image_cropper: ^1.4.0
  syncfusion_flutter_datepicker: ^19.3.57
  roundcheckbox: ^2.0.4+1
  timeline_tile: ^2.0.0
  google_fonts: ^4.0.4
  in_app_review: ^2.0.4
  salomon_bottom_bar: ^3.3.1
  awesome_otp_screen: ^0.0.2
  # onesignal_flutter: ^3.2.7
  # upgrader: ^3.11.1
  # time_range: ^1.0.2
  # first_time_screen: ^1.0.3
#  flutter_html: ^2.2.1

  # dash_chat: ^1.1.15
  # firebase_storage: ^5.2.0
  # cloud_firestore: ^0.14.4
  # image_picker: ^0.6.7+17

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # connectivity_widget: ^0.1.8
  # connectivity_widget:
  #   git:
  #     url: https://github.com/Vanethos/flutter_connectivity_widget.git
  number_inc_dec: ^0.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/gdial.png
    - assets/images/Picture2.png
    - assets/images/pic2.png
    - assets/images/pic3.png
    - assets/images/pic4.png
    - assets/icons/
    - assets/ser/

  fonts:
    - family: Titillium Web
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
    # - family: Poppins-Medium
    #   fonts:
    #     - asset: assets/Poppins-Medium.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
